source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "8.0"

pod 'ModestStoreSDK', :git => 'git@github.com:braintree/paypal-commerce-ios.git'
pod 'BlockRSSParser'

target 'TabBarShop'

post_install do |generate|
   require 'fileutils'
   FileUtils.cp_r('Pods/Target Support Files/Pods-TabBarShop/Pods-TabBarShop-acknowledgements.plist', 'TabBarShop/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
end
