source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "7.0"

pod 'ModestStoreSDK', :git => 'git@github.com:braintree/paypal-commerce-ios.git'
pod 'BlockRSSParser'

target 'ModalShop'

post_install do |generate|
   require 'fileutils'
   FileUtils.cp_r('Pods/Target Support Files/Pods-ModalShop/Pods-ModalShop-acknowledgements.plist', 'ModalShop/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
end

